language: python
notifications:
  email: false

os:
  - linux

python:
  - "3.6"
  # whitelist
# branches:
#   only:
#     - master
# command to install dependencies
install:
    - pip install --upgrade pip
    - pip install ipython
    - pip install -r develop_requirements.txt
    - pip install qcodes # Added explictly here
    - pip install coverage pytest-cov pytest --upgrade
    - pip install codacy-coverage
    - pip install -e .

before_script: # configure a headless display to test plot generation
- "export DISPLAY=:99.0"
- "sh -e /etc/init.d/xvfb start"
- sleep 3 # give xvfb some time to start

# command to run tests
script:
    - py.test pycqed/tests --cov=pycqed --cov-report xml --cov-config=.coveragerc


after_success:
    - pip install codacy-coverage
    # - coverage xml
    - python-codacy-coverage -r coverage.xml
